# Generated by Django 5.0.3 on 2024-03-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_alter_animal_status_species_is_ohio_native_and_more"),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WELLNESS / VACCINE", "Wellness / Vaccine"),
                            ("SURGERY", "Surgery"),
                            ("DIAGNOSIS", "Diagnosis"),
                            ("MEDICATION / TREATMENT", "Medication / Treatment"),
                        ],
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("needs_treatment", models.BooleanField(default=False)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="animals.animal"
                    ),
                ),
            ],
            options={
                "db_table_comment": "Table holds medical record entries.",
            },
        ),
        migrations.DeleteModel(
            name="Vaccine",
        ),
        migrations.AlterModelTableComment(
            name="treatment",
            table_comment=None,
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="cost",
        ),
        migrations.AlterField(
            model_name="treatment",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
