# Generated by Django 5.0.3 on 2024-03-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_medicalrecord_delete_vaccine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="animal",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="description",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="needs_treatment",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="health_report",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="is_vet_cleared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="notes",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="treatment_history",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
    ]
