# Generated by Django 5.0.3 on 2024-03-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_remove_medicalrecord_animal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
