# Generated by Django 5.0.3 on 2024-03-22 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0009_remove_animal_medical_record"),
        ("medical", "0004_alter_medicalrecord_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="animal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="animals.animal",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
