# Generated by Django 5.0.3 on 2024-03-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0005_medicalrecord_animal_medicalrecord_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
    ]
