# Generated by Django 5.0.6 on 2024-06-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0006_delete_medicalrecord"),
        ("people", "0003_person_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRoomUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "q_volunteer",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="people.person",
                    ),
                ),
            ],
        ),
    ]
