# Generated by Django 5.0.2 on 2024-03-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='diet',
            field=models.CharField(choices=[('VEGGIE', 'Veggie'), ('MIXED', 'Mixed'), ('INSECT', 'Insect')], default='MIXED', max_length=80),
        ),
    ]
