# Generated by Django 5.0.2 on 2024-03-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
