services:
  docs:
    image: dragonroost_ng_local_docs
    container_name: dragonroost_ng_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./dragonroost_ng:/app/dragonroost_ng:z
    ports:
      - '9000:9000'
    command: /start-docs
