volumes:
  dragonroost_local_postgres_data: {}
  dragonroost_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: dragonroost_local_django:develop
    container_name: dragonroost_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dragonroost_production_postgres:latest
    container_name: dragonroost_local_postgres
    volumes:
      - dragonroost_local_postgres_data:/var/lib/postgresql/data
      - dragonroost_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
