version: '3.8'
services:
  rescuedb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "apasswordforadb"
      POSTGRES_DB: "rescuedb"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"