version: '3.8'
services:
  app:
    build: .
    container_name: app
    environment:
      SECRET_KEY: test
      DJANGO_SETTINGS_MODULE: "dragonroost.production"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
  # this service will use same image, and once the migration is done it will be stopped
  # app_migrations:
  #   build: .
  #   command: ./manage.py migrate
  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - ./prod_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: apasswordforadb
      POSTGRES_DB: dragondb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI

volumes:
  prod_db_data:
  redis_data: