name: Deploy to Test Environment

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
      - run: echo "Building image now"
      - run: docker compose -f docker-compose.production.yml build
      - run: echo "TODO Tag the image and push to Gitea registry"

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image

    steps:
      - name: Deploy App
      - run: echo "Deploying app now"
      - run: docker compose -f docker-compose.production.yml up -d
