name: Deploy to Test Environment
run-name: ${{ gitea.actor }} is running a Gitea Actions job on server ${{ runner.os }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
      - run: echo "This job was triggered by a ${{ gitea.event_name }} event."
      - name: Check out the repository
        uses: actions/checkout@v4
      - run: echo "The ${{ gitea.repository }} has been cloned."
      - name: Build the Docker image
        run: docker compose -f docker-compose.production.yml build
      - run: echo "The Docker image has been created."
      - run: echo "TODO Tag the image and push to Gitea registry"

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image

    steps:
      - name: Deploy App
        run: docker compose -f docker-compose.production.yml up -d
      - run: echo "The app is now running."
