name: Build and deploy Docker images for Dragonroost.
run-name: ${{ gitea.actor }} is running a Gitea Actions job on server ${{ runner.os }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into RPi and deploy Dragonroost.
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /app/
            sudo rm -rf dragonroost/
            sudo git clone https://github.com/leethobbit/dragonroost.git
            cd dragonroost/
            sudo docker compose -f docker-compose.local.yml up
