apiVersion: v1
kind: ConfigMap
metadata:
  name: dragonroost-config
  namespace: dragonroost
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_NAME: "dragondb"
  DB_USER: "postgres"
  DB_HOST: "db"
  DB_PORT: "5432"
  DJANGO_SETTINGS_MODULE: "dragonroost.production"