apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonroost-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dragonroost
  template:
    metadata:
      labels:
        app: dragonroost
    spec:
      containers:
      - name: dragonroost
        image: dragonroost-app:latest
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: dragonroost-config
          - secretRef:
              name: dragonroost-secrets