apiVersion: v1
kind: Secret
metadata:
  name: dragonroost-secrets
  labels:
    app: dragonroost
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .POSTGRES_PASSWORD | base64 }}
  DJANGO_SECRET_KEY: {{ .DJANGO_SECRET_KEY | base64 }}
  SECRET_KEY: {{ .SECRET_KEY | base64 }}
  DB_PASSWORD: {{ .DB_PASSWORD | base64 }}