# Generated by Django 5.0.3 on 2024-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("date", models.DateField(null=True)),
                ("minutes", models.FileField(upload_to="meetings/%Y")),
            ],
        ),
    ]
