# Generated by Django 5.0.6 on 2024-06-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_meeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
