# Generated by Django 5.0.9 on 2024-11-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('feedback_type', models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('COMPLIMENT', 'Compliment'), ('COMPLAINT', 'Complaint')], default='SUGGESTION', max_length=80)),
                ('feedback', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('meeting_url', models.URLField(default='example.com', verbose_name='Meeting URL')),
                ('minutes', models.FileField(blank=True, upload_to='meetings/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_sponsorship', models.BooleanField(default=False)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.person')),
            ],
        ),
    ]
