# Generated by Django 5.0.9 on 2024-10-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(default='example.com', verbose_name='Meeting URL'),
        ),
    ]
