# Generated by Django 5.0.9 on 2024-11-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='has_breeds',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('origin', models.CharField(blank=True, max_length=80)),
                ('temperament', models.CharField(choices=[('ACTIVE', 'Active'), ('ENERGETIC', 'Energetic'), ('GENTLE', 'Gentle'), ('INDEPENDENT', 'Independent')], default='ACTIVE', max_length=80)),
                ('species', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='animals.species')),
            ],
        ),
    ]
