# Generated by Django 5.0.9 on 2024-11-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_medicalrecord_findings_medicalrecord_problem_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ON_HOLD', 'On Hold'), ('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('FOSTERED', 'Fostered'), ('MEDICAL_HOLD', 'Medical Hold'), ('ADOPTED', 'Adopted'), ('DECEASED', 'Deceased'), ('AMBASSADOR', 'Ambassador')], default='ADOPTABLE', max_length=80),
        ),
    ]
