# Generated by Django 5.0.9 on 2024-11-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_species_has_breeds_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.breed'),
        ),
        migrations.AlterField(
            model_name='species',
            name='class_name',
            field=models.CharField(choices=[('MAMMAL', 'Mammal'), ('REPTILE', 'Reptile'), ('BIRD', 'Bird'), ('AMPHIBIAN', 'Amphibian'), ('INSECT', 'Insect'), ('FISH', 'Fish')], default='REPTILE', max_length=20),
        ),
    ]
