# Generated by Django 5.0.9 on 2024-11-20 15:21

import django_measurement.models
import dragonroost.animals.models
import measurement.measures.mass
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_medicalrecord_options_alter_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_photo',
            field=models.ImageField(blank=True, default=dragonroost.animals.models.random_image, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='starting_weight',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ADOPTED', 'Adopted'), ('AMBASSADOR', 'Ambassador'), ('AVAILABLE', 'Available'), ('DECEASED', 'Deceased'), ('FOSTERED', 'Fostered'), ('MEDICAL_HOLD', 'Medical Hold'), ('ON_HOLD', 'On Hold'), ('QUARANTINE', 'Quarantine')], default='AVAILABLE', max_length=80),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='current_weight',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass),
        ),
    ]
