# Generated by Django 5.0.9 on 2024-12-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_animal_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-intake_date']},
        ),
    ]
