# Generated by Django 5.0.9 on 2024-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
