# Generated by Django 5.0.9 on 2024-10-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_meeting_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='minutes',
            field=models.FileField(null=True, upload_to='meetings/%Y'),
        ),
    ]
