# Generated by Django 5.0.3 on 2024-03-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("MAMMAL", "Mammal"),
                            ("REPTILE", "Reptile"),
                            ("BIRD", "Bird"),
                            ("AMPHIBIAN", "Amphibian"),
                            ("INSECT", "Insect"),
                        ],
                        default="REPTILE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "donation_fee",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                ("intake_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal_photo",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("color", models.CharField(default="None", max_length=80)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("age", models.IntegerField(default=0)),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("VEGGIE", "Veggie"),
                            ("MIXED", "Mixed"),
                            ("INSECT", "Insect"),
                        ],
                        default="MIXED",
                        max_length=80,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="business.location",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="animals.species",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="animals.status",
                    ),
                ),
            ],
            options={
                "db_table_comment": "Holds information about animals",
            },
        ),
    ]
