# Generated by Django 5.0.3 on 2024-03-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_alter_animal_status_species_is_ohio_native_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Medical"),
                            ("BEHAVIORAL", "Behavioral"),
                            ("COMMENT", "Comment"),
                            ("WARNING", "Warning"),
                        ],
                        default="COMMENT",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="", max_length=255)),
                ("initials", models.CharField(default="zz", max_length=20)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animals.animal"
                    ),
                ),
            ],
        ),
    ]
