# Generated by Django 5.0.3 on 2024-03-16 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_animalcomment"),
        ("medical", "0003_remove_medicalrecord_animal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="medical_record",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="medical_record",
                to="medical.medicalrecord",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADOPTABLE", "Adoptable"),
                    ("QUARANTINED", "Quarantined"),
                    ("FOSTERED", "Fostered"),
                    ("MEDICAL_HOLD", "Medical Hold"),
                    ("ADOPTED", "Adopted"),
                ],
                default="ADOPTABLE",
                max_length=80,
            ),
        ),
        migrations.DeleteModel(
            name="AnimalComment",
        ),
    ]
