# Generated by Django 5.0.3 on 2024-03-16 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_animal_medical_record_alter_animal_status_and_more"),
        ("medical", "0004_alter_medicalrecord_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="medical_record",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="medical_record",
                to="medical.medicalrecord",
            ),
        ),
    ]
