# Generated by Django 5.0.3 on 2024-03-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0007_alter_animal_medical_record"),
        ("medical", "0004_alter_medicalrecord_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="medical_record",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_record",
                to="medical.medicalrecord",
            ),
        ),
    ]
