# Generated by Django 5.0.3 on 2024-03-25 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0009_remove_animal_medical_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "health_report",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "treatment_history",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="", max_length=500)),
                ("is_vet_cleared", models.BooleanField(default=False)),
                (
                    "animal",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="animals.animal",
                    ),
                ),
            ],
            options={
                "db_table_comment": "Table holds medical record entries.",
            },
        ),
    ]
