# Generated by Django 5.0.3 on 2024-03-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0011_remove_medicalrecord_health_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="initials",
            field=models.CharField(default="zz", max_length=20),
        ),
    ]
