# Generated by Django 5.0.3 on 2024-05-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0012_medicalrecord_initials"),
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="business.location",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="animals.species",
            ),
        ),
    ]
