# Generated by Django 5.0.3 on 2024-05-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0013_alter_animal_location_alter_animal_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="intake_condition",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("HEALTHY", "Healthy"),
                    ("SICK", "Sick"),
                    ("INJURED", "Injured"),
                ],
                default="HEALTHY",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="intake_type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("OWNER_SURRENDER", "Owner Surrender"),
                    ("STRAY", "Stray"),
                    ("RETURN_TO_RESCUE", "Return to Rescue"),
                    ("BORN_IN_CARE", "Born in Care"),
                ],
                default="OWNER_SURRENDER",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="diet",
            field=models.CharField(
                choices=[
                    ("VEGGIE", "Veggie"),
                    ("MIXED", "Mixed"),
                    ("INSECT", "Insect"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADOPTABLE", "Adoptable"),
                    ("QUARANTINED", "Quarantined"),
                    ("FOSTERED", "Fostered"),
                    ("MEDICAL_HOLD", "Medical Hold"),
                    ("ADOPTED", "Adopted"),
                    ("DECEASED", "Deceased"),
                ],
                default="ADOPTABLE",
                max_length=80,
            ),
        ),
    ]
