# Generated by Django 5.0.3 on 2024-05-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0014_animal_intake_condition_animal_intake_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="diet",
        ),
        migrations.AddField(
            model_name="species",
            name="diet",
            field=models.CharField(
                choices=[
                    ("VEGGIE", "Veggie"),
                    ("MIXED", "Mixed"),
                    ("INSECT", "Insect"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=80,
            ),
        ),
    ]
