# Generated by Django 5.0.3 on 2024-05-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0015_remove_animal_diet_species_diet"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="current_condition",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("HEALTHY", "Healthy"),
                    ("SICK", "Sick"),
                    ("INJURED", "Injured"),
                ],
                default="UNKNOWN",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="diet",
            field=models.CharField(
                choices=[
                    ("VEGGIE", "Veggie"),
                    ("CARNIVORE", "Carnivore"),
                    ("MIXED", "Mixed"),
                    ("INSECT", "Insect"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=80,
            ),
        ),
    ]
