# Generated by Django 5.0.3 on 2024-05-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0017_animal_adopted_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="adopted_date",
            new_name="outcome_date",
        ),
    ]
