# Generated by Django 5.0.3 on 2024-05-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0018_rename_adopted_date_animal_outcome_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="outcome_type",
            field=models.CharField(
                choices=[
                    ("ADOPTION", "Adoption"),
                    ("DIED_IN_CARE", "Died in Care"),
                    ("TRANSFER", "Transfer"),
                    ("RETURN_TO_OWNER", "Return to Owner"),
                ],
                default="ADOPTION",
                max_length=80,
            ),
        ),
    ]
