# Generated by Django 5.0.3 on 2024-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="roles",
            field=models.ManyToManyField(to="people.role"),
        ),
    ]
