# Generated by Django 5.0.9 on 2024-11-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('q_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
