# Generated by Django 5.0.2 on 2024-03-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('ADOPTER', 'Adopter'), ('DONOR', 'Donor'), ('VOLUNTEER', 'Volunteer'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=80)),
            ],
        ),
    ]
