# Generated by Django 5.0.2 on 2024-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='555-5555', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='zip_code',
            field=models.IntegerField(default=44121),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='donotemail@example.com', max_length=254),
        ),
    ]
