# Generated by Django 5.0.2 on 2024-03-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_person_name_person_address_person_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
